FROM whaledo/c-development:latest

#RUN dnf install -y xorriso qemu qemu-system-i386 qemu-system-x86_64 syslinux && dnf clean all
RUN dnf install -y xorriso qemu qemu-system-x86 syslinux && dnf clean all
